### ISSUE TITLE
Upshot error on El Capitan

### ISSUE THREAD

**Issue by ml** [fwenzel/upshot#73]
I just updated the system to El Capitan and started getting this (a message from the console):

```
01/10/15 12:17:02,483 UpShot[8427]: Traceback (most recent call last):
01/10/15 12:17:02,483 UpShot[8427]:   File "/Applications/UpShot.app/Contents/Resources/__boot__.py", line 67, in <module>
01/10/15 12:17:02,483 UpShot[8427]:     _run()
01/10/15 12:17:02,483 UpShot[8427]:   File "/Applications/UpShot.app/Contents/Resources/__boot__.py", line 62, in _run
01/10/15 12:17:02,483 UpShot[8427]:     exec(compile(source, path, 'exec'), globals(), globals())
01/10/15 12:17:02,483 UpShot[8427]:   File "/Applications/UpShot.app/Contents/Resources/upshot.py", line 18, in <module>
01/10/15 12:17:02,483 UpShot[8427]:     import Preferences
01/10/15 12:17:02,483 UpShot[8427]:   File "Preferences.pyc", line 3, in <module>
01/10/15 12:17:02,483 UpShot[8427]:   File "objc/_lazyimport.pyc", line 118, in __getattr__
01/10/15 12:17:02,483 UpShot[8427]:   File "objc/_lazyimport.pyc", line 203, in __calc_all
01/10/15 12:17:02,483 UpShot[8427]: ValueError: Don't know CF type for typestr '^{OpaqueLSSharedFileListItemRef=}', cannot create special wrapper
01/10/15 12:17:02,614 UpShot[8427]: UpShot Error
01/10/15 12:17:02,614 UpShot[8427]: 2015-10-01 12:17:02.614 UpShot[8427:831787] UpShot Error
```

Is it related to the update or something else?

**Comment by codenamestif** [comment]
+1, doesn't work after update

**Comment by fwenzel** [comment]
Oh no, that's ugly -- I don't have an El Capitan device yet but will look when I have updated.

Any coder who may be so inclined, feel free to debug as well.

**Comment by fwenzel** [comment]
Also looks like a bug upstream in pyobjc, so I hope there has been an update there that I can pull in.

**Comment by corvock** [comment]
Any word on if the upstream issue was resolved?

**Comment by joshstrange** [comment]
Any update on this, I just upgraded and I'm really missing UpShot

**Comment by fwenzel** [comment]
I don't know yet if the upstream library has been updated :( I might be able to take a closer look this weekend. Sorry for the delay

**Comment by joshstrange** [comment]
For now you can turn on Dropbox's screenshot option in the "Import" tab of preferences
![Screenshot](https://photos-2.dropbox.com/t/2/AAAa47xxlNoYnjSeSC0vLQFUStdYpS4Z0N69D1iSV5i-FQ/12/2148004/png/32x32/3/1447700400/0/2/Screenshot%202015-11-16%2009.54.15.png/EP7k2QEYirfERCACKAI/xqJvK9hAg1OgFNL3fc7FEkFG1glNaQDUQayzwcHBqhI?size_mode=2&size=1600x1200)

Not perfect as they put it in their frame but that's what I'll use for now until the upstream library is updated. If anyone else knows of any good replacements please post them.

**Comment by danahartweg** [comment]
@fwenzel I did some preliminary testing, and it appears that this is addressed in the [following patch to pyobcj](https://bitbucket.org/ronaldoussoren/pyobjc/issues/126/sharedfilelist-imports-from-pyobjc)... UpShot seems to run just fine after being compiled (but I can't say I tested everything).

However, it hasn't been officially released, which means it's not available to be installed by pip. Since there's really no point in submitting a PR that would tell you to manually install the latest beta of pyobjc with the correct changes (3.1b1), I'm just leaving this note here =)

**Comment by fwenzel** [comment]
Thank you! I have no *major* qualms with shipping an update against an unreleased but working version of pyobjc -- after all, it's better than NOT working at all

**Comment by fwenzel** [comment]
Okay here's an (otherwise unchanged) build of upshot against py2app 0.10 and pyobjc 3.1b1 (both of which are unreleased development versions):

https://github.com/fwenzel/upshot/releases/tag/release-2.2

It works for me locally, anyone want to give it a shot (pun maybe intended)?

**Comment by fwenzel** [comment]
If this seems to work, I'll push it through the update machinery. I'm not the biggest fan of building against dev versions, but "maybe there's a bug in there somewhere" is a lot better than "permanently broken"!

**Comment by fordhurley** [comment]
I'm surprised no one else has commented yet. v2.2 is working perfectly for me as well. :shipit:?
